### ISSUE TITLE
Kafka source should check that required bootstrapServers is in yaml 

### ISSUE THREAD

**Issue by aslom** [knative/eventing-sources#302]
## Expected Behavior

Validate yaml and print useful error message when required parameters are missing

If the field is misnamed or missing then it is connecting to "" and failing with not obvious error ...

## Actual Behavior

```
(base) macs-MacBook-Pro:knative aslom$ k logs kafka-source-strimzi-8gj2f-5867675996-rt58h
Error from server (BadRequest): a container name must be specified for pod kafka-source-strimzi-8gj2f-5867675996-rt58h, choose one of: [receive-adapter istio-proxy] or one of the init containers: [istio-init]
(base) macs-MacBook-Pro:knative aslom$ k logs kafka-source-strimzi-8gj2f-5867675996-rt58h -c receive-adapter
{"level":"info","ts":"2019-03-27T19:02:52.471Z","caller":"receive_adapter/main.go:97","msg":"Starting Apache Kafka Receive Adapter...","adapter":{"BootstrapServers":"","Topics":"","ConsumerGroup":"group9","Net":{"SASL":{"Enable":false,"User":"","Password":""},"TLS":{"Enable":false}},"SinkURI":"http://event-display.default.svc.cluster.local/"}}
{"level":"info","ts":1553713372.4723501,"logger":"fallback","caller":"adapter/adapter.go:92","msg":"Starting with config: {adapter 22 0  0xc00014c480}"}
panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

goroutine 1 [running]:
github.com/knative/eventing-sources/contrib/kafka/pkg/adapter.(*Adapter).Start(0xc00014c480, 0xd4e920, 0xc0000b4078, 0xc00009e6c0, 0x0, 0x0)
	/Users/aslom/Documents/awsm/go/src/github.com/knative/eventing-sources/contrib/kafka/pkg/adapter/adapter.go:106 +0x568
main.main()
	/Users/aslom/Documents/awsm/go/src/github.com/knative/eventing-sources/contrib/kafka/cmd/receive_adapter/main.go:98 +0x5d7
```

## Steps to Reproduce the Problem

  1. Rename or remove bootstrapServers field form kafka source config
  2. Follow steps descrined in README in https://github.com/knative/eventing-sources/tree/master/contrib/kafka/samples

## Additional Info

**Comment by aslom** [comment]
@dubee @matzew Is there some schema/validation tool for yaml config files? It would be great to automatically validate config and print useful messages before using invalid config.

**Comment by aslom** [comment]
The same happens to misnamed topics but error message is better

```
{"level":"info","ts":"2019-03-27T19:13:57.528Z","caller":"receive_adapter/main.go:97","msg":"Starting Apache Kafka Receive Adapter...","adapter":{"BootstrapServers":"my-cluster-kafka-bootstrap.kafka:9092","Topics":"","ConsumerGroup":"group9","Net":{"SASL":{"Enable":false,"User":"","Password":""},"TLS":{"Enable":false}},"SinkURI":"http://event-display.default.svc.cluster.local/"}}
{"level":"info","ts":1553714037.52898,"logger":"fallback","caller":"adapter/adapter.go:92","msg":"Starting with config: {adapter 22 0  0xc00012c480}"}
panic: kafka server: The request attempted to perform an operation on an invalid topic.
```

**Comment by aslom** [comment]
I have tested possible error situations with latest code

For empty strings we get nice validations errors now:

```
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source-empty-strings
spec:
  consumerGroup: KAFKA_CONSUMER_GROUP_NAME
  bootstrapServers:
  topics:
  net:
    sasl:
      enable: KAFKA_SASL_ENABLE
      user: KAFKA_SASL_USERNAME
      password: KAFKA_SASL_PASSWORD
    tls:
      enable: KAFKA_TLS_ENABLE
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: event-display
```

```
$ ko apply -f event-source-empty-strings.yaml
The KafkaSource "kafka-source-empty-strings" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"sources.eventing.knative.dev/v1alpha1", "kind":"KafkaSource", "metadata":map[string]interface {}{"uid":"48516ea6-524d-11e9-a47e-0618ef206bb9", "name":"kafka-source-empty-strings", "namespace":"default", "creationTimestamp":"2019-03-29T18:05:49Z", "annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"sources.eventing.knative.dev/v1alpha1\",\"kind\":\"KafkaSource\",\"metadata\":{\"annotations\":{},\"name\":\"kafka-source-empty-strings\",\"namespace\":\"default\"},\"spec\":{\"bootstrapServers\":null,\"consumerGroup\":\"KAFKA_CONSUMER_GROUP_NAME\",\"net\":{\"sasl\":{\"enable\":\"KAFKA_SASL_ENABLE\",\"password\":\"KAFKA_SASL_PASSWORD\",\"user\":\"KAFKA_SASL_USERNAME\"},\"tls\":{\"enable\":\"KAFKA_TLS_ENABLE\"}},\"sink\":{\"apiVersion\":\"serving.knative.dev/v1alpha1\",\"kind\":\"Service\",\"name\":\"event-display\"},\"topics\":null}}\n"}, "generation":1}, "spec":map[string]interface {}{"consumerGroup":"KAFKA_CONSUMER_GROUP_NAME", "net":map[string]interface {}{"sasl":map[string]interface {}{"enable":"KAFKA_SASL_ENABLE", "password":"KAFKA_SASL_PASSWORD", "user":"KAFKA_SASL_USERNAME"}, "tls":map[string]interface {}{"enable":"KAFKA_TLS_ENABLE"}}, "sink":map[string]interface {}{"apiVersion":"serving.knative.dev/v1alpha1", "kind":"Service", "name":"event-display"}, "topics":interface {}(nil), "bootstrapServers":interface {}(nil)}}: validation failure list:
spec.topics in body must be of type string: "null"
spec.bootstrapServers in body must be of type string: "null"
2019/03/29 14:05:49 error executing 'kubectl apply': exit status 1
```

However if actual parameters (`bootstrapServers` and `topics`) are missing it deploys with no error:

```
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source-missing-required
spec:
  consumerGroup: KAFKA_CONSUMER_GROUP_NAME
  net:
    sasl:
      enable: KAFKA_SASL_ENABLE
      user: KAFKA_SASL_USERNAME
      password: KAFKA_SASL_PASSWORD
    tls:
      enable: KAFKA_TLS_ENABLE
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: event-display
```


``` ko apply -f event-source-missing-required.yaml
kafkasource.sources.eventing.knative.dev/kafka-source-missing-required created
```

and controller fails to create receive adapter with non-descriptive errors

```
ERROR: logging before flag.Parse: E0329 18:11:33.018451       1 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: v1alpha1.KafkaSource.Spec: v1alpha1.KafkaSourceSpec.Net: v1alpha1.KafkaSourceNetSpec.SASL: v1alpha1.KafkaSourceSASLSpec.Enable: ReadBool: expect t or f, but found ", error found in #10 byte of ...|"enable":"KAFKA_SASL|..., bigger context ...|FKA_CONSUMER_GROUP_NAME","net":{"sasl":{"enable":"KAFKA_SASL_ENABLE","password":"KAFKA_SASL_PASSWORD|...
ERROR: logging before flag.Parse: E0329 18:11:33.023135       1 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: v1alpha1.KafkaSource.Spec: v1alpha1.KafkaSourceSpec.Net: v1alpha1.KafkaSourceNetSpec.SASL: v1alpha1.KafkaSourceSASLSpec.Enable: ReadBool: expect t or f, but found ", error found in #10 byte of ...|"enable":"KAFKA_SASL|..., bigger context ...|FKA_CONSUMER_GROUP_NAME","net":{"sasl":{"enable":"KAFKA_SASL_ENABLE","password":"KAFKA_SASL_PASSWORD|...
ERROR: logging before flag.Parse: W0329 18:11:33.023205       1 reflector.go:270] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: watch of *v1alpha1.KafkaSource ended with: very short watch: sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Unexpected watch close - watch lasted less than a second and no items received
ERROR: logging before flag.Parse: E0329 18:11:34.072024       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha1.KafkaSource: v1alpha1.KafkaSourceList.Items: []v1alpha1.KafkaSource: v1alpha1.KafkaSource.Spec: v1alpha1.KafkaSourceSpec.Net: v1alpha1.KafkaSourceNetSpec.SASL: v1alpha1.KafkaSourceSASLSpec.Enable: ReadBool: expect t or f, but found ", error found in #10 byte of ...|"enable":"KAFKA_SASL|..., bigger context ...|FKA_CONSUMER_GROUP_NAME","net":{"sasl":{"enable":"KAFKA_SASL_ENABLE","password":"KAFKA_SASL_PASSWORD|...
ERROR: logging before flag.Parse: E0329 18:11:35.073614       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha1.KafkaSource: v1alpha1.KafkaSourceList.Items: []v1alpha1.KafkaSource: v1alpha1.KafkaSource.Spec: v1alpha1.KafkaSourceSpec.Net: v1alpha1.KafkaSourceNetSpec.SASL: v1alpha1.KafkaSourceSASLSpec.Enable: ReadBool: expect t or f, but found ", error found in #10 byte of ...|"enable":"KAFKA_SASL|..., bigger context ...|FKA_CONSUMER_GROUP_NAME","net":{"sasl":{"enable":"KAFKA_SASL_ENABLE","password":"KAFKA_SASL_PASSWORD|...
```

If I remove placeholder fields then receiver is created but it keeps connecting to server '' then leads to Panic so there is not very useful CrashLoopBackOff

```

```
$ cat event-source-missing-required-minimum.yaml

apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source-missing-required-minimum
spec:
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: event-display

```


```
$ ko apply -f event-source-missing-required-minimum.yaml
kafkasource.sources.eventing.knative.dev/kafka-source-missing-required-minimum created
(base) macs-MacBook-Pro:knative aslom$ k get pods
NAME                                                          READY   STATUS             RESTARTS   AGE
busybox                                                       0/1     Completed          0          10d
kafka-source-missing-required-minimum-6tw9p-8d5c96d94-pxqs8   1/2     CrashLoopBackOff   1          14s
```

```
$ k get pods
NAME                                                          READY   STATUS             RESTARTS   AGE
busybox                                                       0/1     Completed          0          10d

$ k logs kafka-source-missing-required-minimum-6tw9p-8d5c96d94-pxqs8 -c receive-adapter
{"level":"info","ts":"2019-03-29T18:15:36.475Z","caller":"receive_adapter/main.go:97","msg":"Starting Apache Kafka Receive Adapter...","adapter":{"BootstrapServers":"","Topics":"","ConsumerGroup":"","Net":{"SASL":{"Enable":false,"User":"","Password":""},"TLS":{"Enable":false}},"SinkURI":"http://event-display.default.svc.cluster.local/"}}
{"level":"info","ts":1553883336.4762325,"logger":"fallback","caller":"adapter/adapter.go:100","msg":"Starting with config: {adapter 22 0  0xc00014a480}"}
panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

goroutine 1 [running]:
github.com/knative/eventing-sources/contrib/kafka/pkg/adapter.(*Adapter).Start(0xc00014a480, 0xd4e8a0, 0xc0000b4078, 0xc00009e6c0, 0x0, 0x0)
	/Users/aslom/Documents/awsm/go/src/github.com/knative/eventing-sources/contrib/kafka/pkg/adapter/adapter.go:114 +0x568
main.main()
	/Users/aslom/Documents/awsm/go/src/github.com/knative/eventing-sources/contrib/kafka/cmd/receive_adapter/main.go:98 +0x5d7
```

**Comment by aslom** [comment]
Fixed by https://github.com/knative/eventing-sources/issues/302
